# Generated by Django 5.0 on 2023-12-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_same_QR', models.ImageField(blank=True, null=True, upload_to='QR-Code/')),
                ('scan_QR', models.ImageField(blank=True, null=True, upload_to='QR-Code/')),
                ('image_front', models.ImageField(blank=True, null=True, upload_to='image_front/')),
                ('image_behind', models.ImageField(blank=True, null=True, upload_to='image_behind/')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
