# Generated by Django 5.0 on 2023-12-22 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='گروه\u200cبندی')),
                ('slug', models.SlugField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_same_QR', models.ImageField(blank=True, null=True, upload_to='QR-Code/', verbose_name='QrCode کالای مشابه')),
                ('scan_QR', models.ImageField(blank=True, null=True, upload_to='QR-Code/', verbose_name='QRCode خام')),
                ('image_front', models.ImageField(blank=True, null=True, upload_to='image_front/', verbose_name='تصویر از جلوی کالا')),
                ('image_behind', models.ImageField(blank=True, null=True, upload_to='image_behind/', verbose_name='تصویر از پشت کالا')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کالا')),
                ('code', models.CharField(blank=True, max_length=40, null=True, verbose_name='کد کالا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کالا')),
                ('link', models.URLField(blank=True, null=True, verbose_name=' لینک ویدئو توضیحات محصول در آپارات، دیدئو، یوتیوب و ...  ')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='سن')),
                ('box', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع بسته\u200cبندی(نیم\u200cجعبه، نیم\u200cجعبه با طلق و ...')),
                ('variety', models.CharField(blank=True, max_length=100, null=True, verbose_name='ساده، باطری\u200cخور، کنترلی و ... ')),
                ('category', models.CharField(blank=True, choices=[('۱', '۱'), ('۲', '۲')], max_length=100, null=True, verbose_name='دسته\u200cبندی')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت به تومان با حذف سه صفر')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_gather_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
