# Generated by Django 5.0 on 2023-12-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category2',
            name='highlighted',
        ),
    ]
