# Generated by Django 5.0 on 2023-12-19 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_warehouse', '0002_store_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(blank=True, choices=[('۱', '۱'), ('۲', '۲')], max_length=100, null=True, verbose_name='دسته\u200cبندی مربوط به هر صنف '),
        ),
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='قیمت به تومان با حذف سه صفر'),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_gather_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
