# Generated by Django 5.0 on 2023-12-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_warehouse', '0002_remove_category2_highlighted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام کاربر ')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل کارب ')),
                ('message', models.TextField()),
            ],
        ),
    ]
