# Generated by Django 5.0 on 2023-12-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_warehouse', '0003_store_category_store_price_store_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت به تومان با حذف سه صفر'),
        ),
    ]
