# Generated by Django 5.0 on 2023-12-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_warehouse', '0004_comment_date_comment_store_alter_comment_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category2',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
