# Generated by Django 5.0 on 2023-12-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_warehouse', '0004_alter_store_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='سن'),
        ),
        migrations.AddField(
            model_name='store',
            name='box',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع بسته\u200cبندی(نیم\u200cجعبه، نیم\u200cجعبه با طلق و ...'),
        ),
        migrations.AddField(
            model_name='store',
            name='variety',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ساده، باطری\u200cخور، کنترلی و ... '),
        ),
    ]
