# Generated by Django 5.0 on 2023-12-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_warehouse', '0005_store_age_store_box_store_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کالا'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image_behind',
            field=models.ImageField(blank=True, null=True, upload_to='image_behind/', verbose_name='تصویر از پشت کالا'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image_front',
            field=models.ImageField(blank=True, null=True, upload_to='image_front/', verbose_name='تصویر از جلوی کالا'),
        ),
        migrations.AlterField(
            model_name='store',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name=' لینک ویدئو توضیحات محصول در آپارات، دیدئو، یوتیوب و ...  '),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='store',
            name='scan_QR',
            field=models.ImageField(blank=True, null=True, upload_to='QR-Code/', verbose_name='QRCode خام'),
        ),
        migrations.AlterField(
            model_name='store',
            name='scan_same_QR',
            field=models.ImageField(blank=True, null=True, upload_to='QR-Code/', verbose_name='QrCode کالای مشابه'),
        ),
    ]
