# Generated by Django 5.0 on 2023-12-28 12:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_warehouse', '0005_alter_category2_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
