# Generated by Django 5.0 on 2023-12-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_warehouse', '0006_alter_store_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کالا'),
        ),
    ]
