# Generated by Django 5.0.1 on 2024-02-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_warehouse', '0012_alter_store_price_customer_order_credit_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image_behind',
        ),
        migrations.RemoveField(
            model_name='store',
            name='scan_QR',
        ),
        migrations.AlterField(
            model_name='store',
            name='scan_same_QR',
            field=models.ImageField(blank=True, null=True, upload_to='QR-Code/', verbose_name='QrCode اسکن'),
        ),
    ]
