# Generated by Django 5.0.1 on 2024-02-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_warehouse', '0013_remove_store_image_behind_remove_store_scan_qr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='scan_same_QR',
        ),
        migrations.AddField(
            model_name='store',
            name='scan_QR',
            field=models.ImageField(blank=True, null=True, upload_to='QR-Code/', verbose_name='QRCode اسکن'),
        ),
    ]
